let title2 = document.getElementsByTagName("h1")[0];
document.body.addEventListener("click", whenClicked);

function whenClicked(e) {
	let randomNumber = Math.floor(Math.random() * 129);
	let randoClr = randomColors[randomNumber];
	let newColor = randoClr.replace(" ", "")
        document.body.style.backgroundColor = `${newColor}`;	
	title2.innerText = `${randomColors[randomNumber]}`
	
	if(`${newColor}` == "black") {
//		document.body.style.backgroundColor = "black"	
		title2.style.color = "white" 
	}
}


let randomColors = ["Alice Blue",
  "Antique White",
  "Aqua",
  "Aquamarine",
  "Azure",
  "Beige",
  "Bisque",
  "Black",
  "Blanched Almond",
  "Blue",
  "Blue Violet",
  "Brown",
  "Burly Wood",
  "Cadet Blue",
  "Chartreuse",
  "Chocolate",
  "Coral",
  "Cornflower Blue",
  "Cornsilk",
  "Crimson",
  "Cyan",
  "Dark Blue",
  "Dark Cyan",
  "Dark GoldenRod",
  "Dark Gray",
  "Dark Grey",
  "Dark Green",
  "Dark Khaki",
  "Dark Magenta",
  "Dark Orange",
  "Dark Orchid",
  "Dark Red",
  "Dark Salmon",
  "Dark Turquoise",
  "Dark Violet",
  "Deep Pink",
  "Dim Gray",
  "Dim Grey",
  "Dodger Blue",
  "Fire Brick",
  "Floral White",
  "Forest Green",
  "Fuchsia",
  "Gainsboro",
  "Ghost White",
  "Gold",
  "Golden Rod",
  "Gray",
  "Grey",
  "Green",
  "Green Yellow",
  "HoneyDew",
  "Hot Pink",
  "Indian Red",
  "Indigo",
  "Ivory",
  "Khaki",
  "Lavender",
  "Lavender Blush",
  "Lawn Green",
  "Lemon Chiffon",
  "Light Blue",
  "Light Coral",
  "Light Cyan",
  "Light Gray",
  "Light Grey",
  "Light Green",
  "Light Pink",
  "Light Salmon",
  "Light Yellow",
  "Lime",
  "Lime Green",
  "Linen",
  "Magenta",
  "Maroon",
  "Medium Blue",
  "Medium Orchid",
  "Medium Purple",
  "Medium Turquoise",
  "Midnight Blue",
  "Mint Cream",
  "Misty Rose",
  "Moccasin",
  "Navajo White",
  "Navy",
  "Old Lace",
  "Olive",
  "Olive Drab",
  "Orange",
  "Orange Red",
  "Orchid",
  "Pale Green",
  "Pale Turquoise",
  "Papaya Whip",
  "Peach Puff",
  "Peru",
  "Pink",
  "Plum",
  "Powder Blue",
  "Purple",
  "Rebecca Purple",
  "Red",
  "Rosy Brown",
  "Royal Blue",
  "Saddle Brown",
  "Salmon",
  "Sandy Brown",
  "Sea Green",
  "Sea Shell",
  "Sienna",
  "Silver",
  "Sky Blue",
  "Slate Blue",
  "Slate Gray",
  "Slate Grey",
  "Snow",
  "Spring Green",
  "Steel Blue",
  "Tan",
  "Teal",
  "Thistle",
  "Tomato",
  "Turquoise",
  "Violet",
  "Wheat",
  "White",
  "White Smoke",
  "Yellow",
  "Yellow Green",
];

console.log(randomColors.length)
